### ISSUE TITLE
nitorch.core.datasets.download_url name change

### ISSUE THREAD

**Issue by r-gray** [brudfors/UniRes#17]
Hi Mikael, I just ran demo_unires.ipynb and noticed that nitorch.core.datasets.download_url has been changed to, I think, nitorch.core.datasets.fetch_data! Thanks, Robert.

**Comment by brudfors** [comment]
Hi @r-gray! Thanks you very much, I have fixed it now.

**Comment by r-gray** [comment]
Brilliant, thank you!
