### ISSUE TITLE
preprocessing with Label

### ISSUE THREAD

**Issue by jakubMitura14** [brudfors/UniRes#19]
Hello thanks for publishing fantastic algorithm !
I have prostate dataset that I want to use for segmentation - my question is Can I use your tool with labelled dataset?
I have ground truth labels  sampled as t2w image, so in order to be able to use it I need to be able to apply all transformations identically to my labels and t2w - How to achieve it?

**Comment by brudfors** [comment]
Hi @jakubMitura14 

Nice to hear that you find the code useful :)

Yes, you can include labels (ensuring that the affine matrices are modified correctly):

https://github.com/brudfors/UniRes/blob/82d00afd0119f996f38953e25a92f944fdd63fc8/unires/struct.py#L85

For example, if you have a label file `label.nii.gz` and one modality you would specify it as:

```py
from unires.struct import settings as s

s.label = ('label.nii.gz', (0, 0))
```

This function might give some insights into using unires as an api:

https://github.com/brudfors/UniRes/blob/82d00afd0119f996f38953e25a92f944fdd63fc8/unires/_cli.py#L7

Keep in mind that your prostate images need to have good alignment between subjects as unires internal inter-subject alignment method currently only works for brain scans (it uses an atlas-based approach with a T1w brain mean image). That is, this option:

https://github.com/brudfors/UniRes/blob/82d00afd0119f996f38953e25a92f944fdd63fc8/unires/struct.py#L77

needs to be set to False. However, if you have some prostate mean image, it could be used to perform the inter-subject alignment.

**Comment by jakubMitura14** [comment]
I would like to ask something futher - precisely about  "common_output" - it seem fantasic to get all of the data on the same grid - hovewer I do not see exactly how it works?
I seen that I can pass into the preproc function two dimensional list of paths to nifti files - but only one setting file
so I should put the labels into tuple like
```
s.label = ('labelA.nii.gz','labelB.nii.gz' )... ?
```
Also I have t2 (axial coronal, saggital) and adc images labels are associated with t2w image (it was annotated basically on t2 axials) - how to mark it so during registration and resampling labels will be adjusted as the t2w?

Lastly I had done experiment  and all resampled files have been written - but not labels, how to specify where the modified resampled labels should be present?

**Comment by brudfors** [comment]
If you have three images of the same 'repeat' (three T2 scans of different thick-slice direction: coronal, sagittal, axial) and the label is annotated on the axial scan, you would specify this as:

```python
data = [['t2_c.nii.gz', 't2_s.nii.gz', 't2_a.nii.gz']]
s.label = ('label.nii.gz', (0, 2))
```

You have to ensure that your label image is an integer tensor with values `{0, 1, ..., num_labels}`. Meaning that if you have multiple binary masks, you will need to merge these into a categorical one.

**Comment by jakubMitura14** [comment]
perfect, Thanks! and if I want to put whole dataset (given I had done earlier interpatient registration ) on the same grid as described in "common_output" how to pass multiple labels?

**Comment by brudfors** [comment]
UniRes runs on one subject at a time, not on a population. So you would have to call it multiple times, once for each subject.

**Comment by brudfors** [comment]
If no labels are available, then you would just call UniRes w/o labels for those subjects.
